#!/usr/bin/env bash

services=( archlinux centos centos-old ubuntu ubuntu-old ubuntu-wget ubuntu-old-wget )

for service in "${services[@]}" ; do
  echo "${service}"
  # export env might be using for tests
  docker-compose run -e NVH_NODE_MIRROR -e https_proxy "${service}" "$@"
  echo ""
done

echo "macOS"
"$@"
