#!/usr/bin/env bash

services=( archlinux centos centos-old ubuntu-curl ubuntu-old-curl ubuntu-wget ubuntu-old-wget )

for service in "${services[@]}" ; do
  echo "${service}"
  docker-compose run "${service}" "$@"
  echo ""
done

echo "macOS"
"$@"
