#!/usr/bin/env bash

echo ""
echo "To make use of proxy server:"
echo "   export https_proxy=\"$(hostname):8080\""
echo "   export http_proxy=\"$(hostname):8080\""
echo ""
echo "Launching proxy server..."
mitmdump --server-replay-nopop --server-replay proxy~~.dump
